# Lab12 - Q1
    root = LinkedBinaryTree.Node(2)
    root.left = LinkedBinaryTree.Node(7)
    root.right = LinkedBinaryTree.Node(5)
    root.right.left = LinkedBinaryTree.Node(10)
    root.left.left = LinkedBinaryTree.Node(2)
    root.left.right = LinkedBinaryTree.Node(6)
    root.right.right = LinkedBinaryTree.Node(9)
    root.right.right.left = LinkedBinaryTree.Node(4)
    root.left.right.left = LinkedBinaryTree.Node(5)
    root.left.right.right = LinkedBinaryTree.Node(11)
    root.right.right.right = LinkedBinaryTree.Node(100)
    root.left.left.left = LinkedBinaryTree.Node(103)
    root.left.left.right = LinkedBinaryTree.Node(101)
    bin_tree = LinkedBinaryTree(root)
